name: mp-dl-unh
channels:
  - defaults
dependencies:
  - _tflow_select
  - absl-py
  - appnope
  - astor
  - attrs
  - backcall
  - blas
  - bleach
  - c-ares
  - ca-certificates
  - certifi
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - gast
  - gettext
  - glib
  - google-pasta
  - grpcio
  - h5py
  - hdf5
  - icu
  - importlib_metadata
  - intel-openmp
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - libpng
  - libprotobuf
  - libsodium
  - markdown
  - markupsafe
  - mistune
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - nbconvert
  - nbformat
  - ncurses
  - notebook
  - numpy-base
  - openssl
  - opt_einsum
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pip
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - protobuf
  - ptyprocess
  - pygments
  - pyqt
  - pyrsistent
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtpy
  - readline
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sqlite
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - terminado
  - testpath
  - tk
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - pip:
    - cdflib
    - chardet
    - cycler
    - ffnet
    - idna
    - joblib
    - kiwisolver
    - matplotlib
    - matplotlib-venn
    - networkx
    - numpy
    - pyparsing
    - requests
    - scikit-learn
    - spacepy
    - tqdm
    - urllib3

